SELECT EMPLOYEES.LASTNAME, EMPLOYEES.EMPLOYEEID, ORDERS.ORDERID, ORDERS.ORDERDATE
FROM ORDERS  
INNER JOIN EMPLOYEES ON ORDERS.EMPLOYEEID = EMPLOYEES.EMPLOYEEID;
WHERE 

SELECT EMPLOYEES.LASTNAME, EMPLOYEES.EMPLOYEEID, ORDERS.ORDERID, ORDERS.ORDERDATE
FROM EMPLOYEES
LEFT JOIN ORDERS ON EMPLOYEES.EMPLOYEEID =  ORDERS.EMPLOYEEID
ORDER BY EMPLOYEES.EMPLOYEEID;
WHERE

SELECT EMPLOYEES.LASTNAME, EMPLOYEES.EMPLOYEEID, ORDERS.ORDERID, ORDERS.ORDERDATE
FROM ORDERS
RIGHT JOIN EMPLOYEES ON ORDERS.EMPLOYEEID =  EMPLOYEES.EMPLOYEEID
ORDER BY ORDERS.EMPLOYEEID;
WHERE

SELECT COUNT(CUSTOMERID),SHIPPERID 
FROM ORDERS
GROUP BY SHIPPERID;

SELECT *
FROM ORDERS
LIMIT 10;

SELECT MIN(CUSTOMERID)
FROM ORDERS;

SELECT MAX(CUSTOMERID)
FROM ORDERS;

SELECT AVG(CUSTOMERID)
FROM ORDERS;

SELECT SUM(CUSTOMERID)
FROM ORDERS;
