start TRANSACTION;
CREATE DATABASE TESTDB;
ROLLBACK;

START TRANSACTION;
CREATE DATABASE CONCESIONARIO;

-- DROP DATABASE CONCESIONARIO;

USE CONCESIONARIO;

/*CREATE TABLE Vehiculos(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    placa VARCHAR(6) NOT NULL,
    marca VARCHAR(50) NOT NULL,
    kilometraje INT NOT NULL,
    fecha_venta DATE,
    documento_vendedor INT NOT NULL
);*/

CREATE TABLE Vehiculos(
    placa VARCHAR(6) NOT NULL PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,
    kilometraje INT NOT NULL,
    fecha_venta DATE,
    documento_vendedor INT NOT NULL
);

-- DROP TABLE vehiculos; 

ALTER TABLE VEHICULOS 
MODIFY COLUMN DOCUMENTO_VENDEDOR BIGINT NOT NULL;

EXPLAIN VEHICULOS;

ALTER TABLE VEHICULOS 
RENAME COLUMN DOCUMENTO_VENDEDOR TO cc_vendedor;

CREATE TABLE Vehiculos(
    placa VARCHAR(6) NOT NULL PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,
    kilometraje INT NOT NULL,
    fecha_venta DATE,
    documento_vendedor INT NOT NULL
);

ALTER TABLE VEHICULOS
ADD color VARCHAR(10) NOT NULL;

ALTER TABLE VEHICULOS
DROP COLUMN COLOR;